[build]
buildCommand = "npm install --ignore-scripts && npx prisma generate && npm run build"

[deploy]
preDeployCommand = "npx prisma migrate deploy"
startCommand = "NODE_ENV=production npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
